# .github/workflows/sync_notion_posts.yml
name: Sync Notion Posts

on:
  schedule:
    - cron: '0 * * * *' # 매 시간마다 실행
  workflow_dispatch: # 수동 실행

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run sync script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
        run: node sync_notion_posts.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update posts from Notion" -a || echo "No changes to commit"
          git push
